# this is nam eof the workflow that will b edisplayed in actions tab
name: cICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is the environment whee workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "COde Clone from"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build container
        run: echo "build container"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test container
        run: echo "test container"
        
  deploy:
    if: inputs.environment == 'dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy container
        run: echo "deploy container"
  
