# this is nam eof the workflow that will b edisplayed in actions tab
name: cICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "COde Clone from"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build container
        run: echo "build container"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test container
        run: echo "test container"
        
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy container
        run: echo "deploy container"
  
