# This is workflow name
name: hello

on: 
  push:
    branches: [main]

#These are jobs inside workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello $USER"
