# This is workflow name
name: hello

on: 
  push:
    branches: [main]
    paths: 
      - '**.html'

#These are jobs inside workflow
jobs:
  #This is teh name of the job
  greet:
    #This is runner on which job runs
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "hello $USER"
