name: Portfolio

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-page
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      # get access to ur portfolio code via prebuilt actions
      # clones or checkout code where this workflow is written
      - name: Checkout Code
        uses: actions/checkout@v4

      # setup Github Pages
      - name: Setup Github Pages
        uses: actions/configure-pages@v4

      # static code artifacts
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4

      # deploy
      - name: Deploy to github pages
        uses: actions/deploy-pages@v4
